version: 0.1
images:
  - name: "mcr -> aliyun dotnet sdk"
    docker_registry: "mcr.microsoft.com"
    image: "dotnet/sdk"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/dotnet-sdk"
    tag_regex_exclude:
      - ".*preview.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^7\\.0-.*"
      - "^7\\.0$"
      - "^6\\.0-.*"
      - "^6\\.0$"
      - "^5\\.0-.*"
      - "^5\\.0$"
      - "^3\\.1-.*"
      - "^3\\.1$"
  - name: "mcr -> aliyun dotnet runtime"
    docker_registry: "mcr.microsoft.com"
    image: "dotnet/runtime"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/dotnet-runtime"
    tag_regex_exclude:
      - ".*preview.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^7\\.0-.*"
      - "^7\\.0$"
      - "^6\\.0-.*"
      - "^6\\.0$"
      - "^5\\.0-.*"
      - "^5\\.0$"
      - "^3\\.1-.*"
      - "^3\\.1$"
  - name: "mcr -> aliyun dotnet aspnet"
    docker_registry: "mcr.microsoft.com"
    image: "dotnet/aspnet"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/dotnet-aspnet"
    tag_regex_exclude:
      - ".*preview.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^7\\.0-.*"
      - "^7\\.0$"
      - "^6\\.0-.*"
      - "^6\\.0$"
      - "^5\\.0-.*"
      - "^5\\.0$"
      - "^3\\.1-.*"
      - "^3\\.1$"
  - name: "mcr -> aliyun dotnet runtime-deps"
    docker_registry: "mcr.microsoft.com"
    image: "dotnet/runtime-deps"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/dotnet-runtime-deps"
    tag_regex_exclude:
      - ".*preview.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^7\\.0-.*"
      - "^7\\.0$"
      - "^6\\.0-.*"
      - "^6\\.0$"
      - "^5\\.0-.*"
      - "^5\\.0$"
      - "^3\\.1-.*"
      - "^3\\.1$"
  - name: "mcr -> aliyun dotnet runtime-deps"
    docker_registry: "mcr.microsoft.com"
    image: "dotnet/runtime-deps"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/dotnet-runtime-deps"
    tag_regex_exclude:
      - ".*preview.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^7\\.0-.*"
      - "^7\\.0$"
      - "^6\\.0-.*"
      - "^6\\.0$"
      - "^5\\.0-.*"
      - "^5\\.0$"
      - "^3\\.1-.*"
      - "^3\\.1$"

  - name: "mcr -> aliyun vscode base"
    docker_registry: "mcr.microsoft.com"
    image: "vscode/devcontainers/base"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode-devcontainers-base"
    tag_regex_exclude:
      - ".*dev.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^0$"
      - "^alpine$"
      - "^alpine-3.14$"
      - "^alpine-3.13$"
      - "^alpine-3.12$"
      - "^alpine-3.11 $"
      - "^debian$"
      - "^bullseye$"
      - "^debian-11$"
      - "^buster$"
      - "^debian-10$"
      - "^stretch$"
      - "^debian-9$"
      - "^ubuntu$"
      - "^hirsute$"
      - "^ubuntu-21.04$"
      - "^focal$"
      - "^ubuntu-20.04$"
      - "^bionic$"
      - "^ubuntu-18.04$"
  - name: "mcr -> aliyun vscode cpp"
    docker_registry: "mcr.microsoft.com"
    image: "vscode/devcontainers/cpp"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode-devcontainers-cpp"
    tag_regex_exclude:
      - ".*dev.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^0$"
      - "^bullseye&"
      - "^debian-11&"
      - "^buster&"
      - "^debian-10&"
      - "^stretch&"
      - "^debian-9&"
      - "^hirsute&"
      - "^ubuntu-21.04&"
      - "^focal&"
      - "^ubuntu-20.04&"
      - "^bionic&"
      - "^ubuntu-18.04&"
  - name: "mcr -> aliyun vscode dotnet"
    docker_registry: "mcr.microsoft.com"
    image: "vscode/devcontainers/dotnet"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode-devcontainers-dotnet"
    tag_regex_exclude:
      - ".*dev.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^7\\.0-.*"
      - "^7\\.0$"
      - "^6\\.0-.*"
      - "^6\\.0$"
      - "^5\\.0-.*"
      - "^5\\.0$"
      - "^3\\.1-.*"
      - "^3\\.1$"
  - name: "mcr -> aliyun vscode go"
    docker_registry: "mcr.microsoft.com"
    image: "vscode/devcontainers/go"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode-devcontainers-go"
    tag_regex_exclude:
      - ".*dev.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^1"
  - name: "mcr -> aliyun vscode java"
    docker_registry: "mcr.microsoft.com"
    image: "vscode/devcontainers/java"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode-devcontainers-java"
    tag_regex_exclude:
      - ".*dev.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^1-8$"
      - "^11$"
      - "^11-.*"
      - "^12$"
      - "^12-.*"
      - "^13$"
      - "^13-.*"
      - "^14$"
      - "^14-.*"
      - "^15$"
      - "^15-.*"
      - "^16$"
      - "^16-.*"
      - "^17$"
      - "^17-.*"
      - "^8$"
      - "^8-.*"
  - name: "mcr -> aliyun vscode javascript-node"
    docker_registry: "mcr.microsoft.com"
    image: "vscode/devcontainers/javascript-node"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode-devcontainers-javascript-node"
    tag_regex_exclude:
      - ".*dev.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^10$"
      - "^10-.*"
      - "^12$"
      - "^12-.*"
      - "^14$"
      - "^14-.*"
      - "^16$"
      - "^16-.*"
      - "^18$"
      - "^18-.*"
  - name: "mcr -> aliyun vscode php"
    docker_registry: "mcr.microsoft.com"
    image: "vscode/devcontainers/php"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode-devcontainers-php"
    tag_regex_exclude:
      - ".*dev.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^7$"
      - "^7-.*"
      - "^8$"
      - "^8-.*"
  - name: "mcr -> aliyun vscode python"
    docker_registry: "mcr.microsoft.com"
    image: "vscode/devcontainers/python"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode-devcontainers-python"
    tag_regex_exclude:
      - ".*dev.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^3"
  - name: "mcr -> aliyun vscode ruby"
    docker_registry: "mcr.microsoft.com"
    image: "vscode/devcontainers/ruby"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode-devcontainers-ruby"
    tag_regex_exclude:
      - ".*dev.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^2"
      - "^3"
  - name: "mcr -> aliyun vscode rust"
    docker_registry: "mcr.microsoft.com"
    image: "vscode/devcontainers/rust"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode-devcontainers-rust"
    tag_regex_exclude:
      - ".*dev.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^0$"
      - "^1"
  - name: "mcr -> aliyun vscode typescript-node"
    docker_registry: "mcr.microsoft.com"
    image: "vscode/devcontainers/typescript-node"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode-devcontainers-typescript-node"
    tag_regex_exclude:
      - ".*dev.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^10$"
      - "^10-.*"
      - "^12$"
      - "^12-.*"
      - "^14$"
      - "^14-.*"
      - "^16$"
      - "^16-.*"
      - "^18$"
      - "^18-.*"
  - name: "mcr -> aliyun vscode universal"
    docker_registry: "mcr.microsoft.com"
    image: "vscode/devcontainers/universal"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode-devcontainers-universal"
    tag_regex_exclude:
      - ".*dev.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^0$"
      - "^1$"
      - "^2$"

  - name: "dockerhub -> aliyun redis"
    docker_registry: "docker.io"
    image: "library/redis"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/redis"
    tag_regex_exclude:
    tag_regex:
      - "^2$"
      - "^3$"
      - "^4$"
      - "^5$"
      - "^6$"
      - "^7$"
      - "^alpine$"
      - "^alpine3.10$"
      - "^alpine3.11$"
      - "^alpine3.12$"
      - "^alpine3.13$"
      - "^alpine3.14$"
      - "^alpine3.15$"
      - "^alpine3.16$"
      - "^alpine3.17$"
      - "^alpine3.8$"
      - "^alpine3.9$"
      - "^bullseye$"
      - "^buster$"
      - "^latest$"
      - "^nanoserver$"
      - "^stretch$"
      - "^windowsservercore$"
