version: 0.1
images:
  - name: "mcr -> aliyun dotnet sdk"
    docker_registry: "mcr.microsoft.com"
    image: "dotnet/sdk"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/dotnet-sdk"
    tag_regex_exclude:
      - ".*preview.*"
      - ".*rc.*"
    tag_regex:
      - "^latest$"
      - "^7\\.0-\\.*"
      - "^7\\.0$"
      - "^6\\.0-\\.*"
      - "^6\\.0$"
      - "^5\\.0-\\.*"
      - "^5\\.0$"
      - "^3\\.1-\\.*"
      - "^3\\.1$"
  - name: "dockerhub -> aliyun redis"
    docker_registry: "docker.io"
    image: "library/redis"
    target: "registry.cn-hangzhou.aliyuncs.com/newbe36524/redis"
    tag_regex_exclude:
    tag_regex:
      - "^2$"
      - "^3$"
      - "^4$"
      - "^5$"
      - "^6$"
      - "^7$"
      - "^alpine$"
      - "^alpine3.10$"
      - "^alpine3.11$"
      - "^alpine3.12$"
      - "^alpine3.13$"
      - "^alpine3.14$"
      - "^alpine3.15$"
      - "^alpine3.16$"
      - "^alpine3.17$"
      - "^alpine3.8$"
      - "^alpine3.9$"
      - "^bullseye$"
      - "^buster$"
      - "^latest$"
      - "^nanoserver$"
      - "^stretch$"
      - "^windowsservercore$"